apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-basic-ndbymttp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-basic-ndbymttp 
  name: dotnet-basic-ndbymttp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dotnet-basic-ndbymttp
    weight: 100 
